language: node_js
node_js:
  - '8.9.3'

cache:
  directories:
     - ./node_modules

before_script:
  - npm install -g @angular/cli
  - npm install

script:
  - export CHROME_BIN=chromium-browser
  - xvfb-run -a npm run e2e -- --no-progress --config=protractor-ci.conf.js
  - ng build -prod

addons:
  ssh_known_hosts: ssh.davidmiles.se
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
      - sshpass

after_success:
  - bash .travis-deploy.sh
