language: node_js
node_js:
  - '8.9.3'

cache:
  directories:
  - node_modules
before_script:
- npm install -g @angular/cli
- npm install

script: ng build --base-href /davidmiles-angular/ -prod

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: dist
  github_token: $GITHUB_TOKEN
  on:
    branch: master
