language: node_js
node_js:
  - '8.9.3'

cache:
  directories:
  - node_modules
before_script:
- npm install -g @angular/cli
- npm install

script: ng build -prod

addons:
  ssh_known_hosts: ssh.davidmiles.se
  apt:
    packages:
      - sshpass
after_success:
  - export SSHPASS=$SSH_PASS
  - sshpass -e rsync --archive --delete --chmod=Du=rwx,go=rx,Fu=rwx,og=rx "dist/" "$SSH_USER@ssh.davidmiles.se:/www/angular/"

